name: Rickroll

on: [issues]

jobs:
  rickroll:
    runs-on: ubuntu-latest
    steps:
    - name: Post Rickroll
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: "Thanks for the issue! Meanwhile, check out [this resource](https://www.youtube.com/watch?v=dQw4w9WgXcQ)!"
          })
